import ajax from './ajax';
const URL = 'http://47.106.86.139:9010';
export const reqBgImg = data => ajax(data, URL + '/getRandomScreensaver.php', 'GET');
export const reqLogin = data => ajax(data, URL + '/userLogin.php', 'POST');
export const reqGroupLink = data => ajax(data, URL + '/getLinksOfGroup.php', 'GET');
export const reqAddLink = data => ajax(data, URL + '/addLinkOfGroup.php', 'POST');
export const reqUpdateItem = data => ajax(data, URL + '/updateFavoriteLinks.php', 'GET');
export const reqDeleteItem = data => ajax(data, URL + '/deleteLinkOfGroup.php', 'POST');
export const reqQuitGroup = data => ajax(data, URL + '/clearKEY.php', 'GET');
export const reqNewGroup = data => ajax(data, URL + '/generateKEY.php', 'POST');
export const reqJoinGroup = data => ajax(data, URL + '/submitKEY.php', 'POST');
export const reqPushGroup = data => ajax(data, URL + '/addLinkOfGroup.php', 'GET');
export const reqUpdataLink = data => ajax(data, URL + '/updateLinkOfGroup.php', 'POST');
export const reqRegUser = data => ajax(data, URL + '/userRegister.php', 'POST');
export const reqGetHash = data => ajax(data, URL + '/getGroupList.php', 'GET');
